apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpcserver
  labels:
    app: grpcserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpcserver
  template:
    metadata:
      labels:
        app: grpcserver
    spec:
      containers:
      - name: grpc-server
        image: momomengyu/kubernetes-grpctracingserver:part1
        ports:
        - containerPort: 8080
        env:
          - name: JAEGER_SERVICE_NAME
            value: grpcserver
          - name: JAEGER_AGENT_HOST
            value: my-jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
