apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: http-server
        image: momomengyu/kubernetes-httpserver:part2
        ports:
        - containerPort: 8080
