apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpcclient
  labels:
    app: grpcclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcclient
  template:
    metadata:
      labels:
        app: grpcclient
    spec:
      containers:
      - name: grpc-client
        image: momomengyu/kubernetes-grpctracingclient:part1
        ports:
        - containerPort: 8080
        env:
          - name: JAEGER_SERVICE_NAME
            value: grpcserver
          - name: JAEGER_AGENT_HOST
            value: my-jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_TAGS
            value: "version=${VERSION}"
